sudo: false
language: python
python:
  - 2.6
  - 2.7
cache:
  directories:
  - eggs
matrix:
  fast_finish: true
before_install:
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/buildout -c travis.cfg -q
script:
  - bin/test
notifications:
  irc:
  email:
    - maurits@vanrees.org
