sudo: false
language: python
dist: xenial   # required for Python >= 3.7
python:
  - "2.7"
  - "3.6"
  - "3.7"
cache:
  directories:
  - eggs
matrix:
  fast_finish: true
before_install:
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/buildout -c travis.cfg -q
script:
  - bin/code-analysis
  - bin/test
