sudo: false
language: python
python:
  - 2.7
  - 3.6
matrix:
    include:
        - python: "3.7"
          dist: xenial
cache:
  directories:
  - eggs
matrix:
  fast_finish: true
before_install:
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/buildout -c travis.cfg -q
script:
  - bin/code-analysis
  - bin/test
