[tool.towncrier]
# package should be "collective.recipe.backup", but that cannot be imported.
# See https://github.com/hawkowl/towncrier/issues/111
# We cheat here because we do not really need the package name:
package = "towncrier"
issue_format = "`Issue #{issue} <https://github.com/community/collective.recipe.backup/issues/{issue}>`_"
filename = "CHANGES.rst"
directory = "news/"
title_format = "{version} ({project_date})"
# First underline is used for version/date header.
# Second underline is used for the type names (like 'Bug fixes:').
underlines = ["=", ""]

[[tool.towncrier.type]]
directory = "breaking"
name = "Breaking changes:"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "New features:"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug fixes:"
showcontent = true
